import { makeStyles } from '@mui/styles';


export const useStyles = makeStyles({
  content: {
    background: 'white',
    border: 0,
    borderRadius: 3,
    boxShadow: '0 3px 5px 2px rgba(255, 105, 135, .3)',
    color: 'white',
    margin:0,
    height:'60vh',
    width:'60vw',
    display:'flex',
    flexDirection:'column',
    justifyContent:'center',
    margin:'auto',
    marginTop: 20,
  },
  play: {
    height: '20%',
    width: '100%',
    display: 'flex',
    alignItems:'center',
    justifyContent:'center',
  },
  modal: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 700,
    height: 500,
    backgroundColor: 'linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)',
    border: '2px solid #000',
    boxShadow: 24,
    display:'flex',
    flexDirection:'column',
  },
  modalslots: {
    display: 'flex',
    width: '100%',
    height: '70%',
    backgroundColor: 'linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)',
  },
   modalslots1: {
    display: 'flex',
    width: '100%',
    height: '100%',
    backgroundColor: 'linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)',
  },
   modalslots2: {
    display: 'flex',
    width: '100%',
    height: '100%',
    backgroundColor: 'linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)',
  },
   modalslots3: {
    display: 'flex',
    width: '100%',
    height: '100%',
    backgroundColor: 'linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)',
  },
  modalbtns: {
    display: 'flex',
    width: '100%',
    height: '30%',
    backgroundColor: 'linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)',
  },
  modalbtn1: {
    display: 'flex',
    width: '100%',
    height: '100%',
    backgroundColor: 'black',
    alignItems:'center',
    justifyContent: 'center',
  },
  modalbtn2: {
    display: 'flex',
    width: '100%',
    height: '100%',
    backgroundColor: 'black',
    alignItems:'center',
    justifyContent: 'center',
  },
  modalbtn3: {
    display: 'flex',
    width: '100%',
    height: '100%',
    backgroundColor: 'black',
    alignItems:'center',
    justifyContent: 'center',
  },
  spin: {
    width: '30%',
    height: '30%',
  },
  calibrate: {
    width: '60%',
    height: '30%',
  },
  close: {
    width: '40%',
    height: '30%',
  },
  gameover: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 700,
    height: 200,
    backgroundColor: 'white',
    border: '2px solid #000',
    boxShadow: 24,
    display:'flex',
    flexDirection:'column',
  },
  overtxt: {
    textAlign:'center',
  },
  undertxt: {
    textAlign: 'center',
  }
});